name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Dependencies
        run: yarn install --frozen-lockfile

      - name: Build docs
        run: yarn docs

      - name: Publish
        run: bin/publish "${GITHUB_REF:11}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit documentation changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs/*
          commit_message: Update documentation
